---
title: "DSE 6211 Module 04 Lab 04"
author: "Joseph Annand"
date: "2024-02-10"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load libraries


```{r}
library(dplyr)
library(caret)
```


## Import data


```{r}
data <- read.csv("lab_4_data/lab_4_data.csv")
training_ind <- createDataPartition(data$lodgepole_pine,
                                    p = 0.75,
                                    list = F,
                                    times = 1)
```


## Data Pre-processing


```{r}
training_set <- data[training_ind, ]
test_set <- data[-training_ind, ]

top_20_soil_types <- training_set %>%
  group_by(soil_type) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  select(soil_type) %>%
  top_n(20)

training_set$soil_type <- ifelse(training_set$soil_type %in% top_20_soil_types$soil_type,
                                 training_set$soil_type,
                                 "other")

training_set$wilderness_area <- factor(training_set$wilderness_area)
training_set$soil_type <- factor(training_set$soil_type)


onehot_encoder <- dummyVars(~ wilderness_area + soil_type,
                            training_set[, c("wilderness_area", "soil_type")],
                            levelsOnly = T,
                            fullRank = T)

onehot_enc_training <- predict(onehot_encoder,
                               training_set[, c("wilderness_area", "soil_type")])

training_set <- cbind(training_set, onehot_enc_training)


test_set$soil_type <- ifelse(test_set$soil_type %in% top_20_soil_types$soil_type,
                             test_set$soil_type,
                             "other")

test_set$wilderness_area <- factor(test_set$wilderness_area)
test_set$soil_type <- factor(test_set$soil_type)

onehot_enc_test <- predict(onehot_encoder, test_set[, c("wilderness_area", "soil_type")])
test_set <- cbind(test_set, onehot_enc_test)

test_set[, -c(11:13)] <- scale(test_set[, -c(11:13)],
                               center = apply(training_set[, -c(11:13)], 2, mean),
                               scale = apply(training_set[, -c(11:13)], 2, sd))
training_set[, -c(11:13)] <- scale(training_set[, -c(11:13)])
```


## Create R arrays for neural network


```{r}
training_features <- array(data = unlist(training_set[, -c(11:13)]),
                           dim = c(nrow(training_set), 33))
training_labels <- array(data = unlist(training_set[, 13]),
                         dim = c(nrow(training_set)))

test_features <- array(data = unlist(training_set[, -c(11:13)]),
                       dim = c(nrow(test_set), 33))
test_labels <- array(data = unlist(training_set[, 13]),
                     dim = c(nrow(test_set)))
```


## Load libraries and Tensorflow workspace


```{r}
library(reticulate)
library(tensorflow)
library(keras)

use_virtualenv("my_tf_workspace")
```


## Dense Feed-forward Neutral Network


```{r}
model <- keras_model_sequential(list(
  layer_dense(units = 20, activation = "relu"),
  layer_dense(units = 10, activation = "relu"),
  layer_dense(units = 1, activation = "sigmoid")))

compile(model,
        optimizer = "rmsprop",
        loss = "binary_crossentropy",
        metrics = "accuracy")

history <- fit(model, training_features, training_labels,
               epochs = 100, batch_size = 512, validation_split = 0.33)
```


## Exercises


### Question 1


```{r}
plot(history)
```


### Question 2


```{r}
model_2 <- keras_model_sequential(list(
  layer_dense(units = 50, activation = "relu"),
  layer_dense(units = 25, activation = "relu"),
  layer_dense(units = 1, activation = "sigmoid")))

compile(model_2,
        optimizer = "rmsprop",
        loss = "binary_crossentropy",
        metrics = "accuracy")

history_2 <- fit(model_2, training_features, training_labels,
               epochs = 100, batch_size = 512, validation_split = 0.33)

plot(history_2)
```


### Question 3





### Question 4


```{r}
# Model 1
predictions <- predict(model, test_features)
predicted_class <- (predictions[, 1] >= 0.5) * 1

table(predicted_class, test_labels)
model_1_accuracy <- mean(predicted_class == test_labels)
model_1_accuracy

# Model 2
predictions_2 <- predict(model_2, test_features)
predicted_class_2 <- (predictions_2[, 1] >= 0.5) * 1

table(predicted_class_2, test_labels)
model_2_accuracy <- mean(predicted_class_2 == test_labels)
model_2_accuracy
```

